CREATE TABLE [C4G].[rt_rec_data] (
    [id]  INT      IDENTITY (1, 1) NOT NULL,
    [c00] INT      NULL,
    [c01] INT      NULL,
    [c02] DATETIME NULL,
    [c03] INT      NULL,
    [c04] INT      NULL,
    [c05] REAL     NULL,
    [c06] REAL     NULL,
    [c07] REAL     NULL,
    [c08] REAL     NULL,
    [c09] REAL     NULL,
    [c10] REAL     NULL,
    [c11] REAL     NULL,
    [c12] REAL     NULL,
    [c13] REAL     NULL,
    [c14] REAL     NULL,
    [c15] REAL     NULL,
    [c16] REAL     NULL,
    [c17] REAL     NULL,
    [c18] REAL     NULL,
    [c19] REAL     NULL,
    [c20] REAL     NULL,
    [c21] INT      NULL,
    [c22] INT      NULL,
    [c23] INT      NULL,
    [c24] INT      NULL,
    [c25] INT      NULL,
    [c26] INT      NULL,
    [c27] INT      NULL,
    [c28] INT      NULL,
    [c29] INT      NULL,
    [c30] INT      NULL,
    [c31] INT      NULL,
    [c32] INT      NULL,
    [c33] INT      NULL,
    [c34] INT      NULL,
    [c35] INT      NULL,
    [c36] INT      NULL,
    [c37] INT      NULL,
    [c38] INT      NULL,
    CONSTRAINT [PK_rt_rec_data] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_rt_rec_data_c_controller] FOREIGN KEY ([c36]) REFERENCES [C4G].[c_controller] ([id]),
    CONSTRAINT [FK_rt_rec_data_c_rec_variable] FOREIGN KEY ([c01]) REFERENCES [C4G].[c_rec_variable] ([id]),
    CONSTRAINT [FK_rt_rec_data_rt_rec_group] FOREIGN KEY ([c00]) REFERENCES [C4G].[rt_rec_group] ([id])
);



