CREATE TABLE [NGAC].[rt_BeamSetUpLog] (
    [id]               INT           IDENTITY (1, 1) NOT NULL,
    [rt_csv_file_id]   INT           NULL,
    [Date Time]        VARCHAR (MAX) NULL,
    [Tool In Name]     VARCHAR (MAX) NULL,
    [Tool In X]        FLOAT (53)    NULL,
    [Tool In Y]        FLOAT (53)    NULL,
    [Tool In Z]        FLOAT (53)    NULL,
    [Tool In Rx]       FLOAT (53)    NULL,
    [Tool In Ry]       FLOAT (53)    NULL,
    [Tool In Rz]       FLOAT (53)    NULL,
    [Nom tool Name]    VARCHAR (MAX) NULL,
    [Nom Tool X]       FLOAT (53)    NULL,
    [Nom Tool Y]       FLOAT (53)    NULL,
    [Nom Tool Z]       FLOAT (53)    NULL,
    [SetupNo]          VARCHAR (MAX) NULL,
    [Skipped]          VARCHAR (MAX) NULL,
    [nMAXTIPDIAM]      VARCHAR (MAX) NULL,
    [nMINTIPDIAM]      VARCHAR (MAX) NULL,
    [Process Angle]    VARCHAR (MAX) NULL,
    [SlowSearch]       VARCHAR (MAX) NULL,
    [NewManWObj]       VARCHAR (MAX) NULL,
    [Rotation Z setup] VARCHAR (MAX) NULL,
    [Rotation Y setup] VARCHAR (MAX) NULL,
    [TCP Offset X]     FLOAT (53)    NULL,
    [TCP Offset Z]     FLOAT (53)    NULL,
    [Seach Dist]       VARCHAR (MAX) NULL,
    [Meas TCP X]       FLOAT (53)    NULL,
    [Meas TCP Y]       FLOAT (53)    NULL,
    [Meas TCP Z]       FLOAT (53)    NULL,
    [Diff from Nom X]  FLOAT (53)    NULL,
    [Diff from Nom Y]  FLOAT (53)    NULL,
    [Diff from Nom Z]  FLOAT (53)    NULL,
    [Tol Warning]      VARCHAR (MAX) NULL,
    [Update]           VARCHAR (MAX) NULL,
    [Run CheckTCP]     VARCHAR (MAX) NULL,
    [_timestamp]       DATETIME      NULL,
    CONSTRAINT [PK_rt_BeamSetUpLog] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_rt_BeamSetUpLog_rt_csv_file] FOREIGN KEY ([rt_csv_file_id]) REFERENCES [NGAC].[rt_csv_file] ([id])
);



