CREATE TABLE [NGAC].[rt_NutErrLogFile] (
    [id]                        INT           IDENTITY (1, 1) NOT NULL,
    [rt_csv_file_id]            INT           NULL,
    [Date Time]                 DATETIME      NULL,
    [NutID]                     VARCHAR (MAX) NULL,
    [WeldProg]                  INT           NULL,
    [Tool_Nr]                   SMALLINT      NULL,
    [LocPinStatus]              VARCHAR (10)  NULL,
    [NutTubeStatus]             VARCHAR (10)  NULL,
    [FeedStatus]                VARCHAR (30)  NULL,
    [GunExpectPos]              FLOAT (53)    NULL,
    [GunPosToll]                FLOAT (53)    NULL,
    [GunPrePos]                 FLOAT (53)    NULL,
    [GunPostPos]                FLOAT (53)    NULL,
    [PCDVal]                    FLOAT (53)    NULL,
    [PCDValAlaLimit]            FLOAT (53)    NULL,
    [PCDStatus]                 VARCHAR (10)  NULL,
    [SwWeldStaus]               VARCHAR (10)  NULL,
    [NutLTimeOut]               VARCHAR (10)  NULL,
    [ReFeedType]                VARCHAR (30)  NULL,
    [WirePosD_OpeningPos]       FLOAT (53)    NULL,
    [WirePosD_SemiOpeningPos]   FLOAT (53)    NULL,
    [WirePosD_DefaPosTollRange] FLOAT (53)    NULL,
    [WirePosD_GunCalibValue]    FLOAT (53)    NULL,
    [WirePosD_TipZeroOffsetCal] VARCHAR (30)  NULL,
    [WirePosD_TipZeroOffsValue] VARCHAR (30)  NULL,
    [WirePosD_SetupDate]        DATETIME      NULL,
    [WirePosD_CalibTipWeDate]   VARCHAR (MAX) NULL,
    [WirePosD_CalibTipChDate]   DATETIME      NULL,
    [_Col_27]                   VARCHAR (MAX) NULL,
    [_Col_28]                   VARCHAR (MAX) NULL,
    [_Col_29]                   VARCHAR (MAX) NULL,
    [_Col_30]                   VARCHAR (MAX) NULL,
    [_Col_31]                   VARCHAR (MAX) NULL,
    [_timestamp]                DATETIME      NULL,
    CONSTRAINT [PK_rt_NutErrLogFile] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_rt_NutErrLogFile_rt_csv_file] FOREIGN KEY ([rt_csv_file_id]) REFERENCES [NGAC].[rt_csv_file] ([id])
);



