CREATE TABLE [NGAC].[XY_rt_job_breakdown] (
    [id]                 INT          NOT NULL,
    [rt_job_active_id]   INT          NULL,
    [h_alarm_id]         INT          NULL,
    [ts_breakdownStart]  DATETIME     NULL,
    [ts_breakdownEnd]    DATETIME     NULL,
    [ts_breakdownAck]    DATETIME     NULL,
    [ev_breakdownStart]  INT          NULL,
    [val_breakdownStart] INT          NULL,
    [programPointer]     INT          NULL,
    [motionPointer]      INT          NULL,
    [ev_breakdownAck]    INT          NULL,
    [val_breakdownAck]   INT          NULL,
    [index]              VARCHAR (50) NULL,
    [phase1]             VARCHAR (50) NULL,
    [phase2]             VARCHAR (50) NULL,
    [phase3]             VARCHAR (50) NULL,
    [phase4]             VARCHAR (50) NULL,
    [phase5]             VARCHAR (50) NULL,
    [phase6]             VARCHAR (50) NULL,
    [phase7]             VARCHAR (50) NULL,
    [phase8]             VARCHAR (50) NULL,
    [rt_alarm_id]        INT          NULL,
    CONSTRAINT [PK_XY_rt_job_breakdown] PRIMARY KEY CLUSTERED ([id] ASC)
);

