CREATE TABLE [STO].[rt_breakdown] (
    [SOURCE]      VARCHAR (MAX) NULL,
    [OBJECT]      VARCHAR (MAX) NULL,
    [COMMENT]     VARCHAR (MAX) NULL,
    [SEVERITY]    VARCHAR (MAX) NULL,
    [GEOLOACTION] VARCHAR (MAX) NULL,
    [STATUS]      VARCHAR (MAX) NULL,
    [TIMESTAMP]   VARCHAR (MAX) NULL,
    [SUBZONENAME] VARCHAR (MAX) NULL
);

