CREATE TABLE [VISIO].[QiconRawMX7] (
    [WONUM]      VARCHAR (50) NULL,
    [WORKTYPE]   VARCHAR (10) NULL,
    [CHANGEDATE] DATETIME     NULL,
    [JPNUM]      VARCHAR (10) NULL,
    [ANCESTOR]   VARCHAR (50) NULL
);

