CREATE TABLE [dbo].['GreenbeldNa'] (
    [Line]                  NVARCHAR (255) NULL,
    [Station Number]        NVARCHAR (255) NULL,
    [Modezone]              NVARCHAR (255) NULL,
    [Volvo Date]            NVARCHAR (255) NULL,
    [Week]                  NVARCHAR (255) NULL,
    [Day]                   NVARCHAR (255) NULL,
    [Shift]                 FLOAT (53)     NULL,
    [Hour]                  NVARCHAR (255) NULL,
    [Date & Time]           FLOAT (53)     NULL,
    [Numerical Cycle Time]  FLOAT (53)     NULL,
    [Start - Start measure] FLOAT (53)     NULL,
    [Start - End measure]   FLOAT (53)     NULL,
    [Delta SS-SE]           FLOAT (53)     NULL,
    [Waiting Input]         FLOAT (53)     NULL,
    [Waiting Output]        FLOAT (53)     NULL,
    [Technical Cycle Time]  FLOAT (53)     NULL,
    [Line Cycle Time (LCT)] FLOAT (53)     NULL,
    [CT Category]           NVARCHAR (255) NULL,
    [Body Number]           FLOAT (53)     NULL,
    [Body Type]             FLOAT (53)     NULL,
    [Model]                 NVARCHAR (255) NULL,
    [LHD/RHD]               NVARCHAR (255) NULL,
    [2WD/4WD]               NVARCHAR (255) NULL,
    [Sun Roof]              NVARCHAR (255) NULL,
    [Pallet ID]             NVARCHAR (255) NULL,
    [F26]                   NVARCHAR (255) NULL
);

