CREATE TABLE [dbo].['MX7 BOM records$'] (
    [PARENT]     NVARCHAR (255) NULL,
    [ITEMNUM]    NVARCHAR (255) NULL,
    [QUANTITY]   FLOAT (53)     NULL,
    [CXSEQUENCE] FLOAT (53)     NULL,
    [PARINST]    FLOAT (53)     NULL,
    [REMARK]     NVARCHAR (255) NULL,
    [OBJECTNAME] NVARCHAR (255) NULL
);

