CREATE TABLE [dbo].[$VCG_robotlist_GA_17w24] (
    [Project]                          NVARCHAR (255) NULL,
    [Project _Modif]                   NVARCHAR (255) NULL,
    [Building]                         NVARCHAR (255) NULL,
    [Line-_section]                    NVARCHAR (255) NULL,
    [Line-No#]                         NVARCHAR (255) NULL,
    [Stat-No]                          NVARCHAR (255) NULL,
    [IR-No]                            NVARCHAR (255) NULL,
    [Manufacturer]                     NVARCHAR (255) NULL,
    [Robot type]                       NVARCHAR (255) NULL,
    [Controller]                       NVARCHAR (255) NULL,
    [Memory _ext# 4+4Mb]               NVARCHAR (255) NULL,
    [Year of in use]                   NVARCHAR (255) NULL,
    [Function package]                 NVARCHAR (255) NULL,
    [C4G Fpack type]                   NVARCHAR (255) NULL,
    [#]                                NVARCHAR (255) NULL,
    [Tool_Changer]                     NVARCHAR (255) NULL,
    [Toolchanger present but not used] NVARCHAR (255) NULL,
    [Type _Toolchanger]                NVARCHAR (255) NULL,
    [Axis 1_Elec# Safety]              NVARCHAR (255) NULL,
    [Axis 2_Elec# Safety]              NVARCHAR (255) NULL,
    [Axis 3_Elec# Safety]              NVARCHAR (255) NULL,
    [Gun_balancing]                    NVARCHAR (255) NULL,
    [Quiss]                            NVARCHAR (255) NULL,
    [Software]                         NVARCHAR (255) NULL,
    [IP address]                       NVARCHAR (255) NULL,
    [Subnetmask]                       NVARCHAR (255) NULL,
    [Default Gateway]                  NVARCHAR (255) NULL,
    [Mech# _Number_Arm]                NVARCHAR (255) NULL,
    [Linear_axis]                      NVARCHAR (255) NULL,
    [Length_(mm)]                      NVARCHAR (255) NULL,
    [Recup]                            NVARCHAR (255) NULL,
    [Remote_operator_panel]            NVARCHAR (255) NULL,
    [Remark]                           NVARCHAR (255) NULL,
    [F34]                              NVARCHAR (255) NULL,
    [F35]                              NVARCHAR (255) NULL,
    [F36]                              NVARCHAR (255) NULL,
    [F37]                              NVARCHAR (255) NULL,
    [F38]                              NVARCHAR (255) NULL,
    [F39]                              NVARCHAR (255) NULL,
    [F40]                              NVARCHAR (255) NULL,
    [F41]                              NVARCHAR (255) NULL,
    [F42]                              NVARCHAR (255) NULL,
    [F43]                              NVARCHAR (255) NULL,
    [F44]                              NVARCHAR (255) NULL,
    [F45]                              NVARCHAR (255) NULL,
    [F46]                              NVARCHAR (255) NULL,
    [F47]                              NVARCHAR (255) NULL,
    [F48]                              NVARCHAR (255) NULL,
    [F49]                              NVARCHAR (255) NULL,
    [F50]                              NVARCHAR (255) NULL,
    [F51]                              NVARCHAR (255) NULL,
    [F52]                              NVARCHAR (255) NULL,
    [F53]                              NVARCHAR (255) NULL,
    [F54]                              NVARCHAR (255) NULL,
    [F55]                              NVARCHAR (255) NULL,
    [F56]                              NVARCHAR (255) NULL,
    [F57]                              NVARCHAR (255) NULL,
    [F58]                              NVARCHAR (255) NULL,
    [F59]                              NVARCHAR (255) NULL,
    [F60]                              NVARCHAR (255) NULL,
    [F61]                              NVARCHAR (255) NULL,
    [F62]                              NVARCHAR (255) NULL,
    [F63]                              NVARCHAR (255) NULL,
    [F64]                              NVARCHAR (255) NULL,
    [F65]                              NVARCHAR (255) NULL,
    [F66]                              NVARCHAR (255) NULL,
    [F67]                              NVARCHAR (255) NULL,
    [F68]                              NVARCHAR (255) NULL,
    [F69]                              NVARCHAR (255) NULL,
    [F70]                              NVARCHAR (255) NULL,
    [F71]                              NVARCHAR (255) NULL,
    [F72]                              NVARCHAR (255) NULL,
    [F73]                              NVARCHAR (255) NULL,
    [F74]                              NVARCHAR (255) NULL,
    [F75]                              NVARCHAR (255) NULL,
    [F76]                              NVARCHAR (255) NULL,
    [F77]                              NVARCHAR (255) NULL,
    [F78]                              NVARCHAR (255) NULL,
    [F79]                              NVARCHAR (255) NULL,
    [F80]                              NVARCHAR (255) NULL,
    [F81]                              NVARCHAR (255) NULL,
    [F82]                              NVARCHAR (255) NULL,
    [F83]                              NVARCHAR (255) NULL,
    [F84]                              NVARCHAR (255) NULL,
    [F85]                              NVARCHAR (255) NULL,
    [F86]                              NVARCHAR (255) NULL,
    [F87]                              NVARCHAR (255) NULL,
    [F88]                              NVARCHAR (255) NULL,
    [F89]                              NVARCHAR (255) NULL,
    [F90]                              NVARCHAR (255) NULL,
    [F91]                              NVARCHAR (255) NULL,
    [F92]                              NVARCHAR (255) NULL,
    [F93]                              NVARCHAR (255) NULL,
    [F94]                              NVARCHAR (255) NULL,
    [F95]                              NVARCHAR (255) NULL,
    [F96]                              NVARCHAR (255) NULL,
    [F97]                              NVARCHAR (255) NULL,
    [F98]                              NVARCHAR (255) NULL,
    [F99]                              NVARCHAR (255) NULL,
    [F100]                             NVARCHAR (255) NULL,
    [F101]                             NVARCHAR (255) NULL,
    [F102]                             NVARCHAR (255) NULL,
    [F103]                             NVARCHAR (255) NULL,
    [F104]                             NVARCHAR (255) NULL,
    [F105]                             NVARCHAR (255) NULL,
    [F106]                             NVARCHAR (255) NULL,
    [F107]                             NVARCHAR (255) NULL,
    [F108]                             NVARCHAR (255) NULL,
    [F109]                             NVARCHAR (255) NULL,
    [F110]                             NVARCHAR (255) NULL,
    [F111]                             NVARCHAR (255) NULL,
    [F112]                             NVARCHAR (255) NULL,
    [F113]                             NVARCHAR (255) NULL,
    [F114]                             NVARCHAR (255) NULL,
    [F115]                             NVARCHAR (255) NULL,
    [F116]                             NVARCHAR (255) NULL,
    [F117]                             NVARCHAR (255) NULL,
    [F118]                             NVARCHAR (255) NULL,
    [F119]                             NVARCHAR (255) NULL
);

