CREATE TABLE [dbo].[raw_Ultra771] (
    [SpotName]                     CHAR (50)     NULL,
    [InspectionResultName]         CHAR (255)    NULL,
    [EvaluationClass]              CHAR (50)     NULL,
    [AutoComment]                  CHAR (30)     NULL,
    [InspectorComment]             CHAR (50)     NULL,
    [ResultComment]                CHAR (50)     NULL,
    [ResultCommentOperator]        CHAR (50)     NULL,
    [NuggetDiameter]               FLOAT (53)    NULL,
    [NuggetDiameter2]              FLOAT (53)    NULL,
    [InspectionMethod]             CHAR (10)     NULL,
    [PartName]                     CHAR (50)     NULL,
    [InspectionplanName]           CHAR (50)     NULL,
    [GroupOfSpots]                 CHAR (255)    NULL,
    [WeldStation]                  CHAR (50)     NULL,
    [MeasuredThickness]            FLOAT (53)    NULL,
    [NamePlate1]                   CHAR (50)     NULL,
    [MaterialPlate1]               CHAR (50)     NULL,
    [ThicknessPlate1]              FLOAT (53)    NULL,
    [NamePlate2]                   CHAR (50)     NULL,
    [MaterialPlate2]               CHAR (50)     NULL,
    [ThicknessPlate2]              FLOAT (53)    NULL,
    [NamePlate3]                   CHAR (50)     NULL,
    [MaterialPlate3]               CHAR (50)     NULL,
    [ThicknessPlate3]              FLOAT (53)    NULL,
    [Inspector]                    CHAR (50)     NULL,
    [NominalNuggetDiameter]        VARCHAR (255) NULL,
    [InspectionDate]               VARCHAR (255) NULL,
    [InspectionTime]               VARCHAR (255) NULL,
    [NumberOfSpots]                INT           NULL,
    [NumberOfOKSpots]              INT           NULL,
    [NumberOfNOKSpots]             INT           NULL,
    [IndexOfEvaluationClass]       INT           NULL,
    [IndexOfInspectionMethod]      INT           NULL,
    [CorrectProbeUsed]             INT           NULL,
    [UsedProbeName]                CHAR (30)     NULL,
    [UsedProbeNumber]              CHAR (30)     NULL,
    [UsedProbeDiameter]            FLOAT (53)    NULL,
    [UsedProbeFrequency]           FLOAT (53)    NULL,
    [ProbeControl]                 INT           NULL,
    [BackwallEchoCnt]              INT           NULL,
    [FlawEchoCnt]                  INT           NULL,
    [GasporeEchoCnt]               INT           NULL,
    [BackwallAmplitudeDifference1] FLOAT (53)    NULL,
    [BackwallAmplitudeDifference2] FLOAT (53)    NULL,
    [Gain]                         FLOAT (53)    NULL,
    [DisplayDelay]                 FLOAT (53)    NULL,
    [DisplayWidth]                 FLOAT (53)    NULL,
    [SoundVelocity]                FLOAT (53)    NULL,
    [ProbeDelay]                   FLOAT (53)    NULL,
    [UTInstrumentSetting]          CHAR (255)    NULL,
    [UTEvaluationAssistance]       INT           NULL,
    [UTEvaluationAssistanceName]   CHAR (10)     NULL,
    [AutoFreeze]                   INT           NULL,
    [DefinedProbeName]             CHAR (30)     NULL,
    [DefinedProbeNumber]           CHAR (30)     NULL,
    [DefinedProbeDiameter]         FLOAT (53)    NULL,
    [DefinedProbeFrequency]        FLOAT (53)    NULL,
    [EvaluationThreshold]          INT           NULL,
    [EvaluationThresholdFE]        INT           NULL,
    [EvaluationThresholdGP]        INT           NULL,
    [ToleranceOfElectrodeMark]     FLOAT (53)    NULL,
    [ToleranceOfElectrodeMarkMM]   FLOAT (53)    NULL,
    [ToleranceOfGaspore]           FLOAT (53)    NULL,
    [GasporeEchos]                 FLOAT (53)    NULL,
    [MinimumIndentation]           FLOAT (53)    NULL,
    [MinimumIndentationMM]         FLOAT (53)    NULL,
    [IndexOfTestsequence]          INT           NULL,
    [IndexOfPointSequence]         INT           NULL,
    [TestStation]                  CHAR (50)     NULL,
    [StoreOKResult]                INT           NULL,
    [StoreAscanResult]             INT           NULL,
    [ObjectplanProgrammer]         CHAR (50)     NULL,
    [ObjectplanDate]               VARCHAR (255) NULL,
    [ObjectplanTime]               VARCHAR (255) NULL,
    [ObjectplanName]               CHAR (50)     NULL,
    [ObjectplanPath]               VARCHAR (MAX) NULL,
    [Method]                       INT           NULL,
    [SpotWeldType]                 INT           NULL,
    [InspectionplanProgrammer]     CHAR (50)     NULL,
    [InspectionplanDate]           VARCHAR (255) NULL,
    [InspectionplanTime]           VARCHAR (255) NULL,
    [InspectionResult]             INT           NULL,
    [IDInspection]                 INT           NULL,
    [PlanID]                       INT           NULL,
    [PartID]                       INT           NULL,
    [JointID]                      INT           NULL,
    [PartIdentification]           INT           NULL,
    [JointComment]                 CHAR (255)    NULL,
    [ResultFrameNumber]            INT           NULL,
    [FEEvaluationAfterIE]          INT           NULL,
    [USBoxSerialNo]                CHAR (255)    NULL,
    [ExportToCentralDatastore]     INT           NULL,
    [EvaluationParameter]          CHAR (255)    NULL
);

