CREATE TABLE [Tableau].[BT_Last100d_STW040andMAXIMO] (
    [Location]        VARCHAR (255)  NULL,
    [AssetID]         VARCHAR (255)  NULL,
    [Logtype]         VARCHAR (6)    NOT NULL,
    [timestamp]       DATETIME       NULL,
    [Logcode]         VARCHAR (255)  NULL,
    [Severity]        VARCHAR (255)  NULL,
    [logtext]         NVARCHAR (299) NULL,
    [Response(s)]     INT            NULL,
    [Downtime(s)]     INT            NULL,
    [Classification]  NVARCHAR (255) NOT NULL,
    [Subgroup]        NVARCHAR (255) NOT NULL,
    [refId]           INT            NOT NULL,
    [LocationTree]    VARCHAR (MAX)  NULL,
    [ClassTree]       VARCHAR (MAX)  NULL,
    [controller_name] NVARCHAR (256) NULL,
    [controller_type] VARCHAR (6)    NOT NULL,
    [station]         VARCHAR (255)  NULL,
    [Area]            VARCHAR (255)  NULL,
    [Team]            VARCHAR (255)  NULL,
    [Asset_x]         INT            NULL,
    [Asset_y]         INT            NULL,
    [Asset_png]       VARCHAR (MAX)  NULL,
    [Station_x]       INT            NULL,
    [Station_y]       INT            NULL,
    [Station_png]     VARCHAR (MAX)  NULL,
    [Vyear]           INT            NULL,
    [Vweek]           INT            NULL,
    [Vday]            INT            NULL,
    [PLOEG]           VARCHAR (2)    NULL,
    [shift]           VARCHAR (2)    NULL
);

