CREATE TABLE [GLUE].[produktierapport2] (
    [ID]                            INT IDENTITY (1, 1) NOT NULL,
    [geplande_cijfers_OpLijnP4_S1]  INT NOT NULL,
    [geplande_cijfers_OpLijnP4_S2]  INT NOT NULL,
    [geplande_cijfers_OpLijnP4_S3]  INT NOT NULL,
    [OpLijnP4_S1]                   INT NOT NULL,
    [OpLijnP4_S2]                   INT NOT NULL,
    [OpLijnP4_S3]                   INT NOT NULL,
    [geplande_cijfers_FramingP4_S1] INT NOT NULL,
    [geplande_cijfers_FramingP4_S2] INT NOT NULL,
    [geplande_cijfers_FramingP4_S3] INT NOT NULL,
    [FramingP4_S1]                  INT NOT NULL,
    [FramingP4_S2]                  INT NOT NULL,
    [FramingP4_S3]                  INT NOT NULL,
    [geplande_cijfers_WIP_GA_P4]    INT NOT NULL,
    [OKGA_P4]                       INT NOT NULL,
    [geplande_cijfers_OpLijnP3_S1]  INT NOT NULL,
    [geplande_cijfers_OpLijnP3_S2]  INT NOT NULL,
    [geplande_cijfers_OpLijnP3_S3]  INT NOT NULL,
    [OpLijnP3_S1]                   INT NOT NULL,
    [OpLijnP3_S2]                   INT NOT NULL,
    [OpLijnP3_S3]                   INT NOT NULL,
    [geplande_cijfers_FramingP3_S1] INT NOT NULL,
    [geplande_cijfers_FramingP3_S2] INT NOT NULL,
    [geplande_cijfers_FramingP3_S3] INT NOT NULL,
    [FramingP3_S1]                  INT NOT NULL,
    [FramingP3_S2]                  INT NOT NULL,
    [FramingP3_S3]                  INT NOT NULL,
    [geplande_cijfers_WIP_GA_P3]    INT NOT NULL,
    [OKGA_P3]                       INT NOT NULL,
    [geplande_cijfers_WIP_GB]       INT NOT NULL,
    [geplande_cijfers_BB_available] INT NOT NULL,
    [geplande_cijfers_BB_preorder]  INT NOT NULL,
    [geplande_cijfers_5ekraan]      INT NOT NULL,
    [OLGC]                          INT NOT NULL
);

