CREATE TABLE [PJV].[JoiningPointData] (
    [id]                            INT           IDENTITY (1, 1) NOT NULL,
    [joiningModelVariantDistinctId] INT           NULL,
    [isDead]                        INT           NULL,
    [_timestamp]                    DATETIME      NULL,
    [_lasttimestamp]                DATETIME      NULL,
    [POINT_ID]                      VARCHAR (50)  NULL,
    [JOINT_PART_1]                  VARCHAR (250) NULL,
    [JOINT_PART_2]                  VARCHAR (250) NULL,
    [JOINT_PART_3]                  VARCHAR (250) NULL,
    [JOINT_PART_4]                  VARCHAR (250) NULL,
    [JM_X]                          FLOAT (53)    NULL,
    [JM_Y]                          FLOAT (53)    NULL,
    [JM_Z]                          FLOAT (53)    NULL,
    [SPOT_PROCESS_NUMBER]           INT           NULL,
    [SPOT_GEOMETRY_TYPE]            VARCHAR (50)  NULL,
    [PROCESS_LOCATION]              VARCHAR (250) NULL,
    [CAR_SIDE]                      VARCHAR (50)  NULL,
    [VARIANT]                       VARCHAR (50)  NULL,
    [SPOT_WELD_DIAMETER]            FLOAT (53)    NULL,
    [ELECTRODE_INTENDATION]         VARCHAR (50)  NULL,
    [INSUFFICIENT_WELD_SPOT]        VARCHAR (50)  NULL,
    [FUNCT_JOINT_No]                INT           NULL,
    [CONCEQUENCE_CLASS]             VARCHAR (50)  NULL,
    [Color]                         INT           NULL,
    [Color_r]                       INT           NULL,
    [Color_g]                       INT           NULL,
    [Color_b]                       INT           NULL,
    [LAYER_TYPE]                    VARCHAR (50)  NULL,
    [LAYER_NUMBER]                  INT           NULL,
    [POINT_SYMBOL_NUMBER]           INT           NULL,
    [POSITION_TOLERANCE]            VARCHAR (50)  NULL,
    [CO]                            VARCHAR (50)  NULL,
    [CO_INFO]                       VARCHAR (50)  NULL,
    [CO_ID]                         VARCHAR (50)  NULL,
    [CDSID_Last_Modified_By]        VARCHAR (50)  NULL,
    [Joining_Model_Reference]       VARCHAR (50)  NULL,
    [Local_ID]                      VARCHAR (50)  NULL,
    [USED_IN_VEHICLE]               VARCHAR (50)  NULL,
    [WELD_CURVE_ID]                 INT           NULL,
    [WELD_LENGTH_mm]                FLOAT (53)    NULL,
    [WELD_PROCESS_NUMBER]           VARCHAR (50)  NULL,
    [WELD_SIZE_A]                   FLOAT (53)    NULL,
    [WELD_SIZE_S]                   FLOAT (53)    NULL,
    [WELD_CLASS]                    VARCHAR (50)  NULL,
    [ADDITIONAL_DEMANDS]            VARCHAR (50)  NULL,
    [WELD_WIDTH]                    FLOAT (53)    NULL,
    [GLUE_TRAP]                     VARCHAR (50)  NULL,
    [WELD_MATERIAL]                 VARCHAR (50)  NULL,
    [DEMANDS]                       VARCHAR (50)  NULL,
    [rev_created]                   INT           NULL,
    [rev_modified]                  INT           NULL,
    [PART_NAME]                     VARCHAR (50)  NULL,
    [FASTENER_ITEM]                 VARCHAR (50)  NULL,
    [FASTENER_TYPE]                 VARCHAR (50)  NULL,
    [AUX_DEMANDS]                   VARCHAR (50)  NULL,
    [VECTOR_VX_1]                   FLOAT (53)    NULL,
    [VECTOR_VX_2]                   FLOAT (53)    NULL,
    [VECTOR_VX_3]                   FLOAT (53)    NULL,
    [VECTOR_VY_1]                   FLOAT (53)    NULL,
    [VECTOR_VY_2]                   FLOAT (53)    NULL,
    [VECTOR_VY_3]                   FLOAT (53)    NULL,
    [VECTOR_VZ_1]                   FLOAT (53)    NULL,
    [VECTOR_VZ_2]                   FLOAT (53)    NULL,
    [VECTOR_VZ_3]                   FLOAT (53)    NULL,
    [jp_comment]                    VARCHAR (MAX) NULL,
    CONSTRAINT [PK_JoiningPointData] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_JoiningPointData_JoiningModelVariantDistinct] FOREIGN KEY ([joiningModelVariantDistinctId]) REFERENCES [PJV].[JoiningModelVariantDistinct] ([id])
);

