CREATE TABLE [PJV].[ProcessResult] (
    [id]                      INT           IDENTITY (1, 1) NOT NULL,
    [isDead]                  INT           NULL,
    [_timestamp]              DATETIME      NULL,
    [_lasttimestamp]          DATETIME      NULL,
    [joiningPointDataId]      INT           NULL,
    [robotPointId]            INT           NULL,
    [signature]               VARCHAR (MAX) NULL,
    [isMissingOnRobot]        INT           NULL,
    [isOnTwoRobots]           INT           NULL,
    [isDuplicated]            INT           NULL,
    [rev_created]             INT           NULL,
    [rev_modified]            INT           NULL,
    [isMissingJointPointData] INT           NULL,
    [isWrongProcessDataId]    INT           NULL,
    [isMatched]               INT           NULL,
    [isJpdMultipleDefined]    INT           NULL,
    [isTwiceInSequence]       INT           NULL,
    [isPathReversed]          INT           NULL,
    [isMismatchInGeometry]    INT           NULL,
    [areBothPaths]            INT           NULL,
    [deltaWX]                 FLOAT (53)    NULL,
    [deltaWY]                 FLOAT (53)    NULL,
    [deltaWZ]                 FLOAT (53)    NULL,
    [deltaWRX]                FLOAT (53)    NULL,
    [deltaWRY]                FLOAT (53)    NULL,
    [deltaWRZ]                FLOAT (53)    NULL,
    [deltaWSum]               FLOAT (53)    NULL,
    [dirWX]                   VARCHAR (50)  NULL,
    [dirWY]                   VARCHAR (50)  NULL,
    [dirWZ]                   VARCHAR (50)  NULL,
    [deltaTX]                 FLOAT (53)    NULL,
    [deltaTY]                 FLOAT (53)    NULL,
    [deltaTZ]                 FLOAT (53)    NULL,
    [deltaTRX]                FLOAT (53)    NULL,
    [deltaTRY]                FLOAT (53)    NULL,
    [deltaTRZ]                FLOAT (53)    NULL,
    [deltaTSum]               FLOAT (53)    NULL,
    [deltaPathLen]            FLOAT (53)    NULL,
    CONSTRAINT [PK_ProcessResult] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_ProcessResult_JoiningPointData] FOREIGN KEY ([joiningPointDataId]) REFERENCES [PJV].[JoiningPointData] ([id]),
    CONSTRAINT [FK_ProcessResult_RobotPoint] FOREIGN KEY ([robotPointId]) REFERENCES [PJV].[RobotPoint] ([id])
);

